### ISSUE TITLE
NonBlockingClient example

### ISSUE THREAD

**Issue by lake4790k** [marianobarrios/tls-channel#13]
I'm trying to write a non blocking client but when trying to read I keep getting a `NeedsReadException` which doesn't make sense as I understand. Probably I'm doing something wrong, would it be possible to provide a NonBlockingClient example as well that I could just follow.

**Comment by marianobarrios** [comment]
Hi lake,

I just added a non-blocking client example. Thanks for pointing this out, and I hope that helps.

**Comment by lake4790k** [comment]
Many thanks!
