### ISSUE TITLE
Handshake don't work

### ISSUE THREAD

**Issue by Kreatifchk** [marianobarrios/tls-channel#131]
Automatically handskake dont' work.
My code:
`

while (!stop) {

    selector.select();
    Iterator<SelectionKey> iterator = selector.selectedKeys().iterator();
    while (iterator.hasNext()) {
        SelectionKey key = iterator.next();
	iterator.remove();
	if (key.isValid()) {
	try {
	    if (key.isAcceptable()) {
	        SocketChannel socketChannel = ((ServerSocketChannel) key.channel()).accept();
		socketChannel.configureBlocking(false);
		TlsChannel tlsChannel = ServerTlsChannel.newBuilder(socketChannel, context).build();
		SelectionKey newKey = socketChannel.register(selector, SelectionKey.OP_READ);
		connections.put(tlsChannel, new NIOConnection(socketChannel));
		newKey.attach(tlsChannel);
	    }
	    else if (key.isReadable()) {
	        TlsChannel socketChannel = (TlsChannel) key.attachment();
		NIOConnection connection = connections.get(socketChannel);
		int readResult = connection.read();
		if (readResult == RW_READY) {
		    connection.processing();
		    key.interestOps((key.interestOps() ^ SelectionKey.OP_READ) | SelectionKey.OP_WRITE);
		}
		else if (readResult == RW_CLOSE) {
		    socketChannel.close();
		    connections.remove(socketChannel);
		}
	    }
	    else if (key.isWritable()) {
	        TlsChannel socketChannel = (TlsChannel) key.attachment();
	        NIOConnection connection = connections.get(socketChannel);
	        int readResult = connection.write();
	        if (readResult == RW_READY) {
	             key.interestOps((key.interestOps() ^ SelectionKey.OP_WRITE) | SelectionKey.OP_READ);
	        }
	        else if (readResult == RW_CLOSE) {
	            socketChannel.close();
		    connections.remove(socketChannel);
	        }
	    }
         } catch (NeedsReadException e) {
            key.interestOps(SelectionKey.OP_READ);
        } catch (NeedsWriteException  e) {
	    key.interestOps(SelectionKey.OP_WRITE);
        }
    }
}

`

As stated in the documentation, but i when reading, the handshake should occur automatically, but when reading I get encrypted information, approximately this content

> 

**Comment by marianobarrios** [comment]
Hi Сергей,

I see that your program uses a class called NIOConnection, but I am not sure what that... In general TlsChannel is supposed to be used directly.
