### ISSUE TITLE
remove slf4j dependency?

### ISSUE THREAD

**Issue by kortemik** [marianobarrios/tls-channel#138]
it is causing us problems because we use tls-channel together with https://github.com/teragrep/rlp_01 which is then used within logback i.e. https://github.com/teragrep/jla_01 etc logging frameworks which themselves are implementation backends for slf4j. this causes a circular problem because slf4j provider is not yet available when tls-channel tries to use it.

it causes version dependency with slf4j on the logging framework side as well.

please see another justification from https://github.com/jwtk/jjwt/issues/34

**Comment by kortemik** [comment]
with another thought on the subject, i recommend removing logging completely, from the library all together.

**Comment by kortemik** [comment]
i think we will just use shading instead.

**Comment by kortemik** [comment]
it seems shading does not work well enough for slf4j providers even though the api itself is shadeable, therefore reopening this and PRs.

**Comment by marianobarrios** [comment]
Hi Mikko,

Thanks for using the library and bringing this topic. This is something that I never thought about, and I am a bit split, to be honest.

On one hand, logging was useful in debugging the library itself, and I think there is value in those statements, even if usually deactivated. Additionally, there is an optional (but in the same Jar) functionality in `tlschannel.async` that is higher level (i.e., creates threads) and probably needs logging. 

Moving to `java.util.logging` seems to just move the problem: what if someone is creating an appender for that framework?

On the other hard, yes, this is a low-level library and should be usable anywhere.

In any case, I am curious about how the problem materializes. You write that "this causes a circular problem because slf4j provider is not yet available when tls-channel tries to use it". Which is the actual problem? Of course, I am assuming that logging is disabled for tlschannel (that would be clearly some sort of infinite loop).

**Comment by kortemik** [comment]
Hi Mariano,

Thank you for the library, it is really convenient drop-in solution for our use case.

We share the same view on the usefulness of logging for debugging, and that's why we have actually created logback, log4j, java.util.logging (jul) and log4j2 appenders for the reliable event logging protocol (relp).

Definitely the higher level api should have logging available. I share the same view and on the pr #140 where I propose removing logging complete I did not bear to remove the useful printout on https://github.com/marianobarrios/tls-channel/pull/140/files#diff-3430cf034d48177fff61969d06b34add371460990a74dac971db6041233fb82fR503 and converted it to System.err.println, which itself is neither a good solution but just a workaround. However I felt that it is more appropriate to indicate a bad usage and by fixing usage the println would not trigger.

We have not yet tried out what happens with java.util.logging handler (https://github.com/teragrep/jla_04) called appender in that context with the said solution, however it is more likely due to the nature of java.util.logging that we could instruct the users of the library not to configure the handler for our libraries, jla_04, rlp_01 and tls-channel as it would even obvious for them that using the handler for the handler itself is not really something that can work.

At least SLF4J configured with Logback causes following to appear when configured with SLF4J in the appender:

```
SLF4J: A number (1060) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
```

As seen from the link since 1.7.15 SLF4J has tried to address the case for appending before logging is set up. I think they were more concerned about other cases than actual SLF4J implementations using the SLF4J itself. 

We offer drop-in solution by just having the appender jar and it's dependencies in the classpath having a requirement for a version of SLF4J is hindering.

Another and really important topic for us is the reliability of the logging. As seen from the SLF4J printout the calls will be delayed and from the alternative https://www.slf4j.org/codes.html#substituteLogger the logging system is not transactional while being initialized. While reliable event logging protocol by the definition is lossless having this kind of printout appear just because that the implementation itself caused will cause users to suspect the system itself. Of course the code using the SLF4J is capable of causing the same printout but then the cause is real and not by the logging implementation itself.

Thank you for reaching us out!

With kind regards,
Mikko

**Comment by marianobarrios** [comment]
Hi Mikko,

After some tests and consideration, I convinced myself that SLF4J is just problematic for logging from appenders (for the reasons you stated). However, I still think logging is important so, based on your branch, I created [this](https://github.com/marianobarrios/tls-channel/pull/150/), which also migrates the tests to Java Logging. What do you think? your comments are welcome.

Best regards.

**Comment by marianobarrios** [comment]
Thanks for the review. Let's go step by step: I updated the branch and fixed the logging level.

**Comment by marianobarrios** [comment]
About Java Logging: I will be honest, I tried to use it for tests, and could not make it work the way I wanted. As you can see in the tests, it's just sent to SLF4J, and everything controlled in that framework. I would like to make logging configuration out-of-scope if possible... That said, is what you said something that cannot be done by the use of the library, in case they want to use Java Logging?

**Comment by kortemik** [comment]
Please allow me to explain it bit further:

Java Util Logging provides means to configure the framework with two methods via the LogManager class. The LogManager class loads **either** user supplied configurator class that sets the framework's configuration **or** if that is not present it will use logging.properties which can be user supplied as well. Not both, meaning we as a Java Util Logging Handler (appender) provider can not override things programmatically and leave rest for the properties configuration.

This is acceptable in most circumstances and will allow the separation-of-concern approach regarding the configuration. However for a Java Util Logging Handler (appender) use case it might make sense to provide a method to disable the emission of log events completely by installing a Filter (or boolean that toggles logging off all together). If the library would have such capability, it would allow the user to configure the Handler to be used even with FINEST for all logging without impacting the Handler's ability to forward the data.

With current changes I think we will be able to cover all the cases except the user story of "allow configuring all logging to FINEST level" which is bit of a corner-case most likely, but as our users have large and varying code bases we are really keen on the details how everything behaves even in the most exciting configurations.
