### ISSUE TITLE
NeedsTaskException.getTask() returns null object on read operation

### ISSUE THREAD

**Issue by baceto123** [marianobarrios/tls-channel#144]
Hi Mariano,
I just wanted to say a big thanks for the very well done tls-channel lib.
I've been developing a server backend for our PvP mobile game for the last 3 years using tls-channel. Right now we are close to release and I started testing the server with simulated heavy load and the server started hanging. Unfortunately, it's hard to recreate the issue. Sometimes it happens after 7 hours of running under heavy load and sometimes after 12 hours.

This is the info I have at the moment:
* Using tls-channel 0.7.0 in async mode with:
`ServerTlsChannel.newBuilder(socketChannel, sslContext).withRunTasks(false).build();`
* I'm offloading NeedsTaskException.getTask() to a background thread. After the task executes I return to the main thread and retry the operation (read or write)

What happens:
1. I'm doing a Read operation.
2. I get a NeedsTaskException
3. The getTask() method returns null. After that, what I see from the logs is there are more NeedsTaskException for other channels and getTask() returns null for them too.

The main thread goes in a loop and stays in the loop even after I stop all simulated clients from trying to send traffic.

The server logs show that after the first null result from getTask(), the method starts returning null for other channels too.
Also, it looks like the Read method returns the same bytes for some (or all channels?), because the main thread keeps handling messages even though I have stopped all simulated traffic to the server.

If you have any suggestions how to further debug the issue I can run the tests again.
Here's the Read method
```
private void read(final SelectionKey key)
{
  final HPSClient client = (HPSClient)key.attachment();
  
  //System.out.println("READ...");
  try
  {
	  while(true)
	  {
		  readBuffer.clear();

		  final int numRead = client.hpsTlsChannel.read(readBuffer);
		 
		  if(numRead < 1)
		  {
			  if(numRead == -1)
			  {
				  killKey(key, client);
			  }
			  
			  return;
		  }
		  
		  final HPSMessage msg = hpsMsgContainer.getMessage(HPSMessage.MSG_PROTOCOL_READ_DATA, client, numRead);
		  
		  readBuffer.flip();
		  msg.data.put(readBuffer);
		  msg.data.flip();
		  
		  eventSystem.sendMessage(msg);
	  }
  }
  catch (final NeedsReadException ex) 
  {
	  //System.out.println("NeedsReadException...");
	  
	  // In some very rare cases we may need to write
	  if(client.hpsGetWriteQueue().peek() != null)
	  {
		  key.interestOps(SelectionKey.OP_WRITE);
	  }
	  else
	  {
		  key.interestOps(SelectionKey.OP_READ);
	  }
  } 
  catch (final NeedsWriteException ex) 
  {
	  //System.out.println("NeedsWriteException...");
	  key.interestOps(SelectionKey.OP_WRITE);
  }
  catch(final WouldBlockException ex)
  {
	  // Wait for the channel to become ready - do not change key.interestOps
  }
  catch (final NeedsTaskException ex) 
  {
	  final var task = ex.getTask();
	  
	  if(task == null) 
	  {
		  System.out.println("NeedsTaskException getTask() is null");
		  return;
	  }
	  
	  //System.out.println("NeedsTaskException...");
	  final HPSMessage msg = hpsMsgContainer.getMessage(HPSMessage.MSG_EVENT_EXEC_SSL_TASK, client);
	  msg.task = task;
	  
	  eventSystem.sendMessage(msg);
  }
  catch(final IOException ex) 
  {
	  //System.out.println("IO EX: " + ex);
	  //ex.printStackTrace();
	  killKey(key, client);
  }
}
```

**Comment by baceto123** [comment]
I'm looking at TlsChannelImpl.read() where a call to engine.getHandshakeStatus() returns NEED_TASK and this is handled in TlsChannelImpl.handleTask() where a call to engine.getDelegatedTask() obtains a single task, throws NeedsTaskException and then the task should be run in a background thread.

Then, after the background handling of the task, the read() method is called again and engine.getHandshakeStatus() is checked again. 

What I see in the SSLEngine docs is that engine.getDelegatedTask() may return multiple tasks. Is it guaranteed that if a single task is consumed and then run in a background thread, then the internal SSLEngine state would stay consistent and on the next NEED_TASK it would return the remaining task/s and not null?

I found this test:
[https://www.programcreek.com/java-api-examples/?code=Tencent%2FTencentKona-8%2FTencentKona-8-master%2Fjdk%2Ftest%2Fsun%2Fsecurity%2Fpkcs11%2Ffips%2FTestTLS12.java](url)
```
private static void runDelegatedTasks(SSLEngineResult result,
                SSLEngine engine) throws Exception {

            if (result.getHandshakeStatus() == HandshakeStatus.NEED_TASK) {
                Runnable runnable;
                while ((runnable = engine.getDelegatedTask()) != null) {
                    runnable.run();
                }
                HandshakeStatus hsStatus = engine.getHandshakeStatus();
                if (hsStatus == HandshakeStatus.NEED_TASK) {
                    throw new Exception(
                        "handshake shouldn't need additional tasks");
                }
            }
        }
```

All tasks are consumed from getDelegatedTask() before getHandshakeStatus(); is checked again. Unfortunately, the SSLEngine docs don't say anything how the consumed task should be executed in a background thread. Should they be executed in order or can be executed in parallel?

**Comment by baceto123** [comment]
I've modified tls-channel code and made it consume all tasks at once and then run them one by one in the background, but I once again made it hang. What I'm testing now is to directly close the channel if getTask() returns null.

**Comment by marianobarrios** [comment]
Hi and thanks for reporting the issue. `getTask` should never return `null` in the first call after `NeedsTaskException` was thrown. Looking at your code, I would like to discard a concurrency problem: which is the thread structure of your program? When is the main `read` method called? Please remember that selectors are not thread safe.

**Comment by baceto123** [comment]
A single thread (the main thread) performs all operations related to selector.select(), accept(), read(), and write(). I'm very careful about this. I'm using the lmax disruptor library to send message to background threads. To send messages back to the main thread I'm adding them to a ConcurrentLinkedQueue and then calling selector.wakeup() and reading the messages in the main loop before performing selector.selectedKeys().iterator().

Here's what the main loop looks like
```
@Override
public void run()
{
	try
	{
		final long heartBeatMS = eventSystem.getHPSConfig().heartBeatMS;
		
		while(true)
		{
			try
			{
				final int selectedNum = selector.select(heartBeatMS);
			
				// Reads messages from ConcurrentLinkedQueue
				performCommand();
				
				if(selectedNum > 0)
				{
					final Iterator<SelectionKey> it = selector.selectedKeys().iterator();
					
					while(it.hasNext())
					{
						final SelectionKey key = it.next();
						it.remove();
						
						if(false == key.isValid()) 
						{
							continue;
						}
						else 
						{
                                                        // Accept, Read or Write
							performKeyAction(key);
						}
					}
				}
				
				performTimeoutCheck();
			}
			catch(final OutOfMemoryError ome)
			{
				handleOutOfMemoryError("*************** HPS OutOfMemoryError");
			}
		} // end while
	}
	catch(HPSKillException ex)
	{
		System.out.println("Bye!");
	}
	catch(Exception ex)
	{
		ex.printStackTrace();
	}
	
}
```

**Comment by marianobarrios** [comment]
Thanks for the quick response and the code snippet. My concern is what happens between `performKeyAction` and the original `read`. I ask because I don't think the selector key itself is thread safe either. Please let me be honest, your code is a but heterodox with respect to Selector usage; while there is nothing bad in principle with that, it happens to be that Selectors are just inflexible, not thread safe, and can almost always only be used in the canonical ways ([one single-threaded loop with al socket operations in it](https://github.com/marianobarrios/tls-channel/blob/master/src/test/scala/tlschannel/example/NonBlockingServerWithOffLoopTasks.java)).

**Comment by baceto123** [comment]
This is the performKeyAction method

```
private void performKeyAction(final SelectionKey key)
{
	if(key.isReadable())
	{
		read(key);
	}
	else if(key.isWritable())
	{
		write(key);
	}
	else if(key.isAcceptable())
	{
		accept(key);
	}
}
```

and this is the current read() method

```
private void read(final SelectionKey key)
{
	final HPSClient client = (HPSClient)key.attachment();
	
	//System.out.println("READ...");
	try
	{
		while(true)
		{
			readBuffer.clear();
			final int numRead = client.hpsTlsChannel.read(readBuffer);
			
			if(numRead < 1)
			{
				if(numRead == -1)
				{
					killKey(key, client);
				}
				
				return;
			}
			
			final HPSMessage msg = hpsMsgContainer.getMessage(HPSMessage.MSG_PROTOCOL_READ_DATA, client, numRead);
			
			readBuffer.flip();
			msg.data.put(readBuffer);
			msg.data.flip();
			
			eventSystem.sendMessage(msg);
		}
	}
	catch (final NeedsReadException ex) 
	{
		//System.out.println("NeedsReadException...");
		
		// In some very rare cases we may need to write
		if(client.hpsGetWriteQueue().peek() != null)
		{
			key.interestOps(SelectionKey.OP_WRITE);
		}
		else
		{
			key.interestOps(SelectionKey.OP_READ);
		}
	} 
	catch (final NeedsWriteException ex) 
	{
		//System.out.println("NeedsWriteException...");
		key.interestOps(SelectionKey.OP_WRITE);
	}
	catch(final WouldBlockException ex)
	{
		// Wait for the channel to become ready - do not change key.interestOps
	}
	catch (final NeedsTaskException ex) 
	{
		final var task = ex.getTask();
		
		if(task == null) // Invalid task
		{
			killKey(key, client);
			return;
		}
		
		//System.out.println("NeedsTaskException...");
		final HPSMessage msg = hpsMsgContainer.getMessage(HPSMessage.MSG_EVENT_EXEC_SSL_TASK, client);
		msg.task = task;
		
		eventSystem.sendMessage(msg);
	}
	catch(final IOException ex) 
	{
		//System.out.println("IO EX: " + ex);
		//ex.printStackTrace();
		killKey(key, client);
	}
}
```

**Comment by marianobarrios** [comment]
Probably something I should have asked before: could you tell me exactly which JDK version you are using (and having problems)?

**Comment by baceto123** [comment]
```
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment Corretto-20.0.1.9.1 (build 20.0.1+9-FR)
OpenJDK 64-Bit Server VM Corretto-20.0.1.9.1 (build 20.0.1+9-FR, mixed mode, sharing)
```
This is the Amazon's ARM version of OpenJDK.
Today I didn't have time to do any tests, but tomorrow I'll be back at it.

**Comment by marianobarrios** [comment]
Reading the main [the main documentation of SSLEngine](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/javax/net/ssl/SSLEngine.html), I found that:
> The application should continue obtaining delegated tasks until no more exist, and try the original operation again.

I think this is clear enough. I so created [this branch](https://github.com/marianobarrios/tls-channel/pull/147) that just treats tasks as a collection.

I don't know if this will solve your problem, but it should at least change it, because `null` task simply cannot happen any more now. As expected, in the official tests the number of tasks returned is always exactly one. 

Would you mind testing with this versions?

Best regards.

**Comment by baceto123** [comment]
Mariano,
I have found the issue and it's not related to tls-channel. The server code had a bug in a loop, which created a lot of new objects and this made the jvm memory constrained. 

The issue with SSLEngine.getDelegatedTask() is that instead of throwing OutOfMemoryError it returns null, when the jvm is memory constrained.

You can close this issue and delete the branch you've created. 
Sorry for bothering you.

**Comment by marianobarrios** [comment]
No problem. Thanks for your report anyway.
