### ISSUE TITLE
Static Stackless Flow Control Exceptions

### ISSUE THREAD

**Issue by squarewav** [marianobarrios/tls-channel#148]
Have you considered using static exceptions for flow control like:

```
static final class StacklessException extends Exception {
    public StacklessException(String msg) { super(msg); }
    public Throwable fillInStackTrace() { return this; }
}
static final StacklessException NEEDS_WRITE_EXCEPTION = new StacklessException("NEEDS_WRITE_EXCEPTION");

... then in your code just throw it without calling new ...

    if (c == 0)
        throw NEEDS_WRITE_EXCEPTION;
```

As you know creating exceptions with `new` is literally 100x more expensive than creating a regular Object. Even with overriding fillInStackTrace it's still like 20x more expensive. If you use a static instance, there is virtually zero performance penalty.

You have quite a few flow-control exceptions that don't hold state so they're all candidates for static instances. And there might be some that are holding state that is not critical in which case you could drop the state and go static.

Just a thought. Nice project.

**Comment by marianobarrios** [comment]
Hi, thanks for your comments. Yes, in principle what you say makes sense. I have just created a [pull request](https://github.com/marianobarrios/tls-channel/pull/151) with that. However, I failed to see any measurable performance improvement in the tests. Do you have a workflow in which you think this can be relevant?

**Comment by squarewav** [comment]
I'm not really familiar with tls-channel so I don't have any hard data to offer.

But just from browsing the code it seems that some of these exceptions are being thrown in loops. I have seen instances where performance is greatly improved by removing object creation in tight loops.

What can certainly be measured, and what I have measured myself recently, is the difference between `try { throw new StacklessException(); } catch` VS `try { throw STATIC_EXCEPTION; } catch`. I don't recall exact numbers but I remember it being vaguely 20 times slower to call new.

Some people frown on using exceptions for flow control at all. Personally I think it's fine provided that they are at least stackless (meaning they use `fillInStackTrace() { return this; }`) like you're already doing. And if they don't hold state, I don't really see a downside to making them static even if they're not thrown in loops (like `EofException` and probably elsewhere in your code).

**Comment by marianobarrios** [comment]
I don't think that it's possible to have an exception in tlschannel thrown and caught in a tight loop, because we are doing encryption and IO, which are relatively slow, and the loop won't be tight any more...

About the immutability of the exceptions, it's true that we don't have any specific state, but if you look at `Throwable`, you will see that the class is indeed mutable. Having strange behavior due to this would be extremely disconcerting for users; that's why I think this change would require a performance benefit measurable in at lest some use case.
