### ISSUE TITLE
An example for how to use this with AsyncHttpClient

### ISSUE THREAD

**Issue by mridang** [marianobarrios/tls-channel#15]
This library seems very promising. Any idea on how this can be used with https://github.com/AsyncHttpClient/async-http-client 

I'm not very familiar with TLS and SSL and so it seems very hard to wire this up. 

Any help would be much appreciated.

**Comment by marianobarrios** [comment]
Hi Mridang,

As far as I can see, that library is specifically designed to work on top of Netty. So while I think that tls-channel would be a better choice 😄, I don't think there is much to do...

Regards.
