### ISSUE TITLE
Alternative to DirectBufferDeallocator

### ISSUE THREAD

**Issue by mitchjs** [marianobarrios/tls-channel#153]
Hi, 
I want to use this library code, but my JVM doesn't have "sun.misc" available
I'm locked in to JVM 1.8 (embedded device)
any suggestions?

i changed this code in class DirectBufferAllocator just to make it run

`@Override
  public void free(ByteBuffer buffer) {

	// GC does it
	buffer = null;
	  
	// this does not work in NX MASTER
	// do not wait for GC (and finalizer) to run
    //deallocator.deallocate(buffer);
  }`

dont think this is a solution...
memory just draining too

(0000177582) Memory Available = 399114240 <380928>
(0000178600) Memory Available = 398606336 <507904>
(0000179599) Memory Available = 398098432 <507904>
(0000180600) Memory Available = 397590528 <507904>
(0000181600) Memory Available = 397209600 <380928>
(0000182584) Memory Available = 396828672 <380928>
(0000183600) Memory Available = 396320768 <507904>
(0000184599) Memory Available = 395812864 <507904>
(0000185600) Memory Available = 395431936 <380928>
and so on

i see the buffer(s) are constantly being created/freed
that make sense?

thanks
Mitch

**Comment by marianobarrios** [comment]
Hi Mitch. Thanks for your comment. If for whatever reason you need normal heap buffers, you can always just build the channel like this:
```
TlsChannel tlsChannel = ServerTlsChannel
    .newBuilder(rawChannel, sslContext)
    .withEncryptedBufferAllocator(new HeapBufferAllocator())
    .build();
```

Would that work?

That said, the plan allocator would probably be a better default...

**Comment by marianobarrios** [comment]
Please see [this pull request](https://github.com/marianobarrios/tls-channel/pull/155).

**Comment by mitchjs** [comment]
Thank you... i have it working... i still have some thoughts about the initial buffer size, ill make a new issue...
