### ISSUE TITLE
Initial Buffer Size

### ISSUE THREAD

**Issue by mitchjs** [marianobarrios/tls-channel#156]
Question,

in class TlsChannelImpl(), there is a buffersInitialSize = 4096;
i have debugged and found that it always much larger than 4096...
should the initial buffer size come from:

SSLSession session = engine.getSession();
int networkBufferSize = session.getPacketBufferSize();
int minimumApplicationBufferSize = session.getApplicationBufferSize();

I did try it, it worked of course, and i didnt see resize called once

i made inEncrypted and outEncrypted buffers the networkBufferSize
and the inPlain buffer minimumApplicationBufferSize

or is this not important..

Mitch

**Comment by marianobarrios** [comment]
Hi Mitch,

Thanks for your message. Is your point that the initial size should be bigger? We could do it, but at the cost of allocating more memory that may not be used is messages come in practice small. Please note that.`SSLSession.getPacketBufferSize()` is a theoretical maximum, and does not reflect anything about the network. Same for `getApplicationBufferSize`.

**Comment by mitchjs** [comment]
ok, im learning all this as I go... crypto stuff not my forte :)
i found, that in my system it ended up resizing a few times... and thought maybe be bigger
so the GC doesnt have to deal with the discarded buffers for bigger buffers

-Mitch

**Comment by marianobarrios** [comment]
But if know, from your use case, that it will end up bigger, you can just set the initial value to something different to, as you say, avoid GC.
