### ISSUE TITLE
Trouble getting TLS connection 2nd time

### ISSUE THREAD

**Issue by mitchjs** [marianobarrios/tls-channel#157]
So how im using this is, i get a standard socket connected
then i switch over to TLS via  tlsChannel = ClientTlsChannel.newBuilder(socketChannel, _sslContext).withRunTasks(false).build();
and it all works... i successfully get a TLS secured socket
but if i try to disconnect, and start over it fails
to disconnect i just do a close on the socket (java.nio.channels.SocketChannel .close())
then wait... and restart the process, i get socket connected, but cant get the tlschannel going
its also very hard to debug :)
it also happens if i disconnect the device (pull ethernet out), the socket does close, and code tries to get it going,
socket connects, but tls channel fails....
do i need to do anything with tlschannel to have it ready for another connection?
i wait 15 seconds after disconnect, before retry

ok, while debugging,  it sometimes works.... so there is some delay, that i need
this one gonna be hard to figure out :(

i'll keep at it, and if you have any ideas.... toss em in

thanks
mitch

**Comment by marianobarrios** [comment]
Hi Mitch,

In case you need help, I would really need to see the code that is not working, ideally a minimum case, otherwise it's not really possible...

**Comment by mitchjs** [comment]
yes... i can try to give you what im dealing with
there is a bit of code that was not written by me in this project, called; nioengine
it's a wrapper around all the java.nio socket stuff and incorporates the tls-cannel
i spend some time, and for the heck of it, switched out tls-channel for the niobaswell code
as you mentioned similar code in your read me... its working perfectly... i connect, then disconnect, then reconnect and so forth and its re-establishes the secure socket every time

let me zip up the code, so you can at least see... i would like to have tls-channel working.

there is nothing i have to do special, to have tls-channel ready for another connection,
right?
