### ISSUE TITLE
Selector is not triggering

### ISSUE THREAD

**Issue by erdemtan9** [marianobarrios/tls-channel#19]
I'm using tls channel client with selector. If server send packets back to back, selector is usually not triggering. 

If WINDOW_UPDATE, PRIORITY, HEADER AND CONTINUATION like the picture below, it's problem.
![PROBLEM](https://user-images.githubusercontent.com/60364055/115574036-f192fb80-a2c9-11eb-90e7-212eb718bf94.PNG)

If WINDOW_UPDATE, PRIORITY, HEADER AND CONTINUATION like the picture below, it's OK.
![OK](https://user-images.githubusercontent.com/60364055/115574090-ff488100-a2c9-11eb-941f-439a5a9e5ba7.PNG)

Do you have a solution for that?

**Comment by marianobarrios** [comment]
Hi Erdem,

I would need the source code that experiments the problem in order to attempt a diagnosis.
