### ISSUE TITLE
"Latest" marker is still on release 0.9.0

### ISSUE THREAD

**Issue by qpButterfleyes** [marianobarrios/tls-channel#261]
Hi Mariano,
is it by means that release 0.9.0 is still marked "Latest" although there is a release 0.9.1 for some months now?
In case you recommend to use version 0.9.0 rather than 0.9.1, I'd be glad to find a related info in the release notes.
But maybe it's just by mistake?

**Comment by marianobarrios** [comment]
The latest 0.9.1. This is fixed now. Apparently GitHub used to do this automatically, and now is a manual setting. Thanks!
