### ISSUE TITLE
AsynchronousTlsChannelGroup could use a constructor with ExecutorService

### ISSUE THREAD

**Issue by davyboyhayes** [marianobarrios/tls-channel#267]
Now Java 21 supports virtual threads `Executors.newVirtualThreadPerTaskExecutor()`, rather than bind the caller to the ThreadPoolExecutor, we could allow them to supply their own:
```java
    public AsynchronousTlsChannelGroup(ExecutorService executor) {
        this.id = globalGroupCount.getAndIncrement();
        this.loggedTaskWarning = new AtomicBoolean();
        this.timeoutExecutor = new ScheduledThreadPoolExecutor(1, (runnable) -> new Thread(runnable, String.format("async-channel-group-%d-timeout-thread", this.id)));
        this.selectorThread = new Thread(this::loop, String.format("async-channel-group-%d-selector", this.id));
        this.pendingRegistrations = new ConcurrentLinkedQueue();
        this.shutdown = AsynchronousTlsChannelGroup.Shutdown.No;
        this.selectionCount = new LongAdder();
        this.startedReads = new LongAdder();
        this.startedWrites = new LongAdder();
        this.successfulReads = new LongAdder();
        this.successfulWrites = new LongAdder();
        this.failedReads = new LongAdder();
        this.failedWrites = new LongAdder();
        this.cancelledReads = new LongAdder();
        this.cancelledWrites = new LongAdder();
        this.registrations = new ConcurrentHashMap();
        this.currentReads = new LongAdder();
        this.currentWrites = new LongAdder();

        try {
            this.selector = Selector.open();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        this.timeoutExecutor.setRemoveOnCancelPolicy(true);
        this.executor = executor;
        this.selectorThread.start();
    }

    public AsynchronousTlsChannelGroup(int nThreads) {
        this(new ThreadPoolExecutor(nThreads, nThreads, 0L, TimeUnit.MILLISECONDS, new LinkedBlockingQueue(nThreads * 32), (runnable) -> new Thread(runnable, String.format("async-channel-group-%d-handler-executor", this.id)), new ThreadPoolExecutor.CallerRunsPolicy()));
    }

    public AsynchronousTlsChannelGroup() {
        this(Runtime.getRuntime().availableProcessors());
    }
```

**Comment by marianobarrios** [comment]
HI David,

This looks like an interesting forward-compatibility idea. However, while implementing it, it got me thinking. What would be the use case? Virtual threads are a performance advantage when you have thousand of threads. So instead of implementing some complicated event mechanism in order to reduce threads, you can use virtual threads and keep your programming model simple. However here we already have the event mechanism in place... 

Do you see any real-world scenario in which virtual threads would be a performance advantage?

**Comment by davyboyhayes** [comment]
I am looking at this in the context of an application that provides a Postgres Wire Protocol layer, of which TLS negotiation and communication is key. In this situation, we may have hundreds or more clients connected at once, but unlikely they are all actively communicating at the same time. By using Virtual Threads, I can support a higher number of concurrent but non-active connections, using [1].

However, I think it is less about supporting Virtual Threads, and more about being forward compatible as you say.

I am still in an explorartory phase, so I have no real world numbers to back this up, but in my experience within my company, we see better resource utilisation using Virtual Threads than traditional OS level threads.

[1] - https://gavinray97.github.io/blog/postgres-wire-protocol-jdk-21#step-11---initial-server-skeleton

**Comment by marianobarrios** [comment]
Thanks for the context. My point is that the number of clients plays no role here, as TLSChannel will only create one per CPU (hundreds at most).

**Comment by davyboyhayes** [comment]
Forgive my ignorance (I've not had chance to fully dive into this code), but will we not have a TLSChannel per client that connects to a server implementing this library? If so, then the number of TLSChannel's could grow significantly more than one per CPU, and certainly I'd like to support more than one per CPU core (which I grant I could support through the int constructor)

**Comment by marianobarrios** [comment]
Yes, you will have on TLSChannel per client, but a reasonable usage would have only one, global, AsynchronousTlsChannelGroup. That class is heavy: it contains a Selector and runs a selector thread (outside of the pool). It's supposed to be a singleton.

**Comment by davyboyhayes** [comment]
Ahhh, I've dived further into this code... so you're using the ExecutorService on a per read/write basis, in which case it makes sense to use a ThreadPool default limited to the number of cores available (as more than that can't be executed at once). Adding an ability to future prrof may be desireable, but I am happy to resolve this as won't do regardless.
