### ISSUE TITLE
Call to Class.getMethod causing issue on GraalVM

### ISSUE THREAD

**Issue by jyemin** [marianobarrios/tls-channel#27]
On https://github.com/marianobarrios/tls-channel/blob/master/src/main/java/tlschannel/util/DirectBufferDeallocator.java#L34, there is a call to Class.getMethod: `Class.forName("sun.nio.ch.DirectBuffer").getMethod("cleaner", (Class<?>[]) null)`. The next line is `Class.forName("sun.misc.Cleaner").getMethod("clean")`.  

Is there any particular reason to pass `null` as the value of the varargs parameter in the first line?  It's not incorrect, but I think it's unnecessary, and is causing at least one user problems when used with GraalVM.  See https://jira.mongodb.org/browse/JAVA-4309 (the MongoDB Java driver vendors this library), and the resulting GraalVM issue at https://github.com/oracle/graal/issues/3815.

Hopefully the GraalVM issue will be fixed, but I'd like to work around it by removing the `null` parameter in our vendored copy of your library, and upstream the change here if you're willing.  What do you think?

**Comment by marianobarrios** [comment]
Hi Jeff,

Thanks for the report. I briefly tried to reproduce it with GraalVM, without success. But in any case, yes, it's unnecessary. I just removed it. The fix is both in master and back-ported to the 0.4 branch (as 0.4.2) -- so you have it already when/if you "re-vendor".

Regards.

**Comment by jyemin** [comment]
Thanks!  We are much obliged to you.
