### ISSUE TITLE
ClientTlsChannel.Builder.withEngineFactory?

### ISSUE THREAD

**Issue by Erhannis** [marianobarrios/tls-channel#40]
`ServerTlsChannel.Builder` has `.withEngineFactory` - is there a particular reason why `ClientTlsChannel.Builder` doesn't?  (Like, is it not safe, or broken, or something?  Or, just hasn't been done?)

**Comment by Erhannis** [comment]
Upon closer inspection, I do notice that the Client Builder constructor can accept an Engine directly, and it's configured a little differently, internally - though I'm not yet clear on exactly why.  Given that you can pass in an Engine, it's not as much of a problem that the `.withEngineFactory` method is absent, I suppose.  If there's some deep-rooted reason for the difference, though, I'd be interested in hearing it.

**Comment by marianobarrios** [comment]
The difference is that servers have the capability (using SNI) of using different engines according to what the client indicates, that's the reason for the factory, to implement such flexibility. For clients everything is simpler as they just use a fixed engine. This is just TLS/SSL logic, not specific to this library.

**Comment by Erhannis** [comment]
Ok, thanks!
