### ISSUE TITLE
How to Contribute

### ISSUE THREAD

**Issue by oldfishdk** [marianobarrios/tls-channel#41]
Hi @marianobarrios this library is really great and saved me tons of times. Now that I am thinking of some changes that is also useful to be applied, but didn't see anywhere on how I can contribute. Just wondering could you please provide some guideline and/or instructions?

**Comment by marianobarrios** [comment]
I accept pull requests. I would suggest that, if the change is minor, please just send it. And if the change is somewhat big, maybe it's more efficient to first share the idea (before investing time), or a half-done pull request to show the concept...

**Comment by oldfishdk** [comment]
Thanks for the response. I will try to make PRs for minor changes and look forward to hearing comments from you.
