### ISSUE TITLE
multi-threading example

### ISSUE THREAD

**Issue by kortemik** [marianobarrios/tls-channel#98]
I created a multi-threading version of a NIO server application here https://github.com/teragrep/rlp_03/blob/multi-thread/src/main/java/com/teragrep/rlp_03/SocketProcessor.java#L109

However I can't simply get around the idea how the tls-channel would fit into the picture because I offload the connection processing after the accepting and creating the socket (runAcceptSelector) to dedicated thread selectors (runMessageSelector) which are interested in their own share of sockets.

Would it be possible to get consulting on the matter?

**Comment by marianobarrios** [comment]
Thanks for your interest in the library. I don't see your program as doing anything special that prevents the use of the library. You can just wrap [the newly accepted socket](https://github.com/teragrep/rlp_03/blob/multi-thread/src/main/java/com/teragrep/rlp_03/SocketProcessor.java#L198) with a ServerTlsChannel, right after that line...
